- name: Initial Server Setup
  hosts: all
  become: yes

  vars_files:
    - secrets/loki-secrets.yml

  vars:
    admin_user_name: adminuser
    admin_ssh_public: "~/.ssh/id_rsa_adminuser_main-server.pub"
    deployer_user_name: deployeruser
    deployer_ssh_public: "~/.ssh/id_rsa_deployeruser_main-server.pub"
    deployer_ssh_public_cicd: "~/.ssh/id_rsa_github_actions.pub"
    deployer_user_id: 1001
    ansible_become_flags: '-l'

  roles:
    - security
    - monitoring
    - podman

  tasks:
    - name: 1. Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
      tags:
        - update

    - name: 2. Install acl package for filesystem permissions
      apt:
        name: acl
        state: present
      tags:
        - packages
        - acl

    - name: 3. Enable acl support in /etc/fstab dynamically
      ansible.posix.mount:
        path: /
        src: "{{ item.device }}"
        fstype: "{{ item.fstype }}"
        opts: "{{ item.options.split(',') | union(['acl']) | join(',') }}"
        state: present
      loop: "{{ ansible_facts['mounts'] }}"
      when: item.mount == "/"
      register: fstab_result
      tags:
        - acl

    - name: 4. Remount root filesystem to apply acl changes
      ansible.builtin.command:
        cmd: mount -o remount /
      when: fstab_result.changed
      tags:
        - acl

    - name: 5. Allow unprivileged users to bind to privileged ports (for rootless Traefik)
      ansible.posix.sysctl:
        name: net.ipv4.ip_unprivileged_port_start
        value: '80'
        state: present
        reload: yes
      tags:
        - security
        - network

    - name: 6. Install unattended-upgrades package
      apt:
        name: "unattended-upgrades"
        state: present
      tags:
        - packages

    - name: 7. Enable lingering for deployer user to allow systemd services without login
      ansible.builtin.command:
        cmd: "loginctl enable-linger {{ deployer_user_name }}"
      changed_when: false
      tags:
        - user

    - name: 8. Create a new user with sudo privileges
      user:
        name: "{{ admin_user_name }}"
        state: present
        groups: sudo
        append: yes
        shell: /bin/bash
      tags:
        - user
  
    - name: 9. Add SSH authorized key for the new admin user
      ansible.posix.authorized_key:
        user: "{{ admin_user_name }}"
        key: "{{ lookup('file', admin_ssh_public) }}"
        state: present
      tags:
        - ssh

    - name: 10. Create a dedicated, non-interactive user for deployments
      user:
        name: "{{ deployer_user_name }}"
        state: present
        groups: podman
        append: yes
        shell: /bin/bash
      tags:
        - user

    - name: 11. Add SSH authorized key for the new deployer user
      ansible.posix.authorized_key:
        user: "{{ deployer_user_name }}"
        key: "{{ lookup('file', deployer_ssh_public) }}"
        state: present
      tags:
        - ssh

    - name: 12. Add dedicated CI/CD SSH authorized key for the deployer user
      ansible.posix.authorized_key:
        user: "{{ deployer_user_name }}"
        key: "{{ lookup('file', deployer_ssh_public_cicd) }}"
        state: present
      when: deployer_ssh_public_cicd != ""
      tags:
        - ssh
        - cicd

    - name: 13. Configure automatic security updates
      template:
        src: templates/50unattended-upgrades.j2
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        owner: root
        group: root
        mode: '0644'
      tags:
        - updates

    - name: 14. Copy the systemd service file for the user podman socket
      ansible.builtin.template:
        src: templates/podman-user-socket.service.j2
        dest: /etc/systemd/system/podman-user-socket.service
        mode: '0644'

    - name: 15. Reload systemd daemon to recognize the new service
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: 16. Enable and start the podman-user-socket service
      ansible.builtin.systemd:
        name: podman-user-socket.service
        enabled: yes
        state: started