- name: Initial Server Setup
  hosts: all
  become: yes

  vars_files:
    - secrets/loki-secrets.yml

  vars:
    deployer_user_name: deployeruser
    deployer_ssh_public: "~/.ssh/id_rsa_deployeruser_main-server.pub"
    deployer_ssh_public_cicd: "~/.ssh/id_rsa_github_actions.pub"
    deployer_user_id: 1001

  roles:
    - security
    - monitoring
    - podman

  tasks:
    - name: 5. Allow unprivileged users to bind to privileged ports (for rootless Traefik)
      ansible.posix.sysctl:
        name: net.ipv4.ip_unprivileged_port_start
        value: '80'
        state: present
        reload: yes
      tags:
        - security
        - network

    - name: 7. Enable lingering for deployer user to allow systemd services without login
      ansible.builtin.command:
        cmd: "loginctl enable-linger {{ deployer_user_name }}"
      changed_when: false
      tags:
        - user

    - name: 8. Create a dedicated, non-interactive user for deployments
      user:
        name: "{{ deployer_user_name }}"
        state: present
        groups: podman
        append: yes
        shell: /bin/bash
      tags:
        - user

    - name: 9. Add SSH authorized key for the new deployer user
      ansible.posix.authorized_key:
        user: "{{ deployer_user_name }}"
        key: "{{ lookup('file', deployer_ssh_public) }}"
        state: present
      tags:
        - ssh

    - name: 10. Add dedicated CI/CD SSH authorized key for the deployer user
      ansible.posix.authorized_key:
        user: "{{ deployer_user_name }}"
        key: "{{ lookup('file', deployer_ssh_public_cicd) }}"
        state: present
        # To do: Allow multiple services
        key_options: 'command="/usr/bin/systemctl --user restart textreview-backend.service",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty'
      when: deployer_ssh_public_cicd != ""
      tags:
        - ssh
        - cicd

    - name: 12. Copy the systemd service file for the user podman socket
      ansible.builtin.template:
        src: templates/podman-user-socket.service.j2
        dest: /etc/systemd/system/podman-user-socket.service
        mode: '0644'

    - name: 13. Reload systemd daemon to recognize the new service
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: 14. Enable and start the podman-user-socket service
      ansible.builtin.systemd:
        name: podman-user-socket.service
        enabled: yes
        state: started