---
collections:
  - name: community.general
  - name: grafana.grafana
  - name: containers.podman

roles:
  # --- 'pjurke' ---
  - src: https://github.com/pjurke/ansible-role-security.git
    scm: git
    name: security
  - src: https://github.com/pjurke/ansible-role-podman.git
    scm: git
    name: podman
  - src: https://github.com/pjurke/ansible-role-traefik.git
    scm: git
    name: traefik
  - src: https://github.com/pjurke/ansible-role-monitoring.git
    scm: git
    name: monitoring
  - src: https://github.com/pjurke/ansible-role-github-runner.git
    scm: git
    name: github-runner
  - src: https://github.com/pjurke/ansible-role-philipjurke.git
    scm: git
    name: philipjurke

  # --- 'text-review' ---
  - src: https://github.com/text-review/ansible-role-textreview.git
    scm: git
    name: textreview